config/routes.rb
Rails.application.routes.draw do
  
  resources :arrows
  resources :score_types

  resources :scores do 
    member do
      get 'puntuar'
      post 'puntuar'
      post 'add_arrows'
    end
  end

  mount Tolk::Engine => '/tolk', :as => 'tolk'
  devise_for :users

  root 'home#index'

   resources :android do
     collection do
       get 'acceso'
       post 'acceso'
       get 'getsesiones'
       post 'getsesiones'
    end
  end

  resources :home do
     collection do
       get 'index'
    end
  end

  resources :headers

end

app/models/score.rb
class Score < ActiveRecord::Base
	belongs_to :user
	belongs_to :score_type
	has_many   :arrows, dependent: :destroy
	validates :score_type, :name, :user_id, presence: true

	enum state: [:started, :ended, :deleted]

	before_create :do_create_tasks

	scope :published, -> { where(published: true) }

	private
		def do_create_tasks
			# marcar como comenzada
			self.state = Score.states[:started]
			# marcar como privada por defecto
			self.published = false
			# establecemos valores iniciales
			self.points = self.x_count = self.ten_count = self.nine_count = 0
    		self.average = 0.0
		end

	public

		def puntos_ronda_anterior
			return 0	
		end

		def parcial
			return 0
		end

end

app/models/score_type.rb
class ScoreType < ActiveRecord::Base
	has_many :scores

	scope :published, -> { where(published: true) }

	def self.import_old_cats
		TipoTirada.all.each do |tt|
			self.where( name: tt.nombre, 
						arrows: tt.numflechas, 
						distance_1: tt.dist1, 
						distance_2: tt.dist2, 
						distance_3: tt.dist3,
						distance_4: tt.dist4,
						target_1: tt.dia1,
						target_2: tt.dia2,
						target_3: tt.dia3,
						target_4: tt.dia4,
						old_type_id: tt.id).first_or_create
		end
	end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  layout 'app'
  before_action :authenticate_user!
  before_action :set_score, only: [:show, :edit, :update, :destroy, :puntuar, :add_arrows]

  def puntuar
    @arrows = @score.arrows
  end

  def add_arrows
    params[:arrow].each_pair do |param,arrow|
      value = Arrow.get_arrow_value(arrow)
      Arrow.create(score_id: @score.id, value: value, arrow: arrow)
      # acutalizamos datos del score
      @score.points += value
      @score.x_count += 1 if params[:arrow] == 'X'
      @score.ten_count += 1 if value == 10
      @score.nine_count += 1 if value == 9
      @score.average = (@score.points.to_f / @score.arrows.count.to_f).to_f.round(2)
      @score.save
    end
  end

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new()
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)
    @score.user_id = current_user.id
    respond_to do |format|
      if @score.save
        format.html { redirect_to puntuar_score_path(@score) }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:name, :score_type_id, :user_id, :state, :published, :points, :average, :x_count, :ten_count, :nine_count)
    end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_datos_parciales_score.html.erb
<div id="datos-score">
	<div class="row">
		<div class="col-md-3">
			<h4>
				<div class="inline"><%= t 'score.anterior' %></div>
				<div id="ronda_anterior" class="inline"><%= @score.puntos_ronda_anterior %></div>
				<div class="inline"><%= t 'score.pts' %></div>
			</h4>
		</div>
		<div class="col-md-10">
			<h1>
				<div id="acumulacion" class="inline"><%= @score.points %></div>
				<div class="inline"><%= t 'score.pts' %></div>
			</h1>
		</div>
		<div class="col-md-3">
			<h4>
				<div id="parcial" class="inline"><%= @score.parcial %></div>
				<div class="inline"><%= t 'score.pts' %></div>
			</h4>
		</div>
		<div class="col-md-3">
			<h4>
				<div class="inline"><%= t 'score.media' %></div>
				<div id="media" class="inline"><%= @score.average %></div>
				<div class="inline"><%= t 'score.pts' %></div>
			</h4>
		</div>


	<%= link_to t('score.reset'), '#', on_click: 'resetear();', class: 'resetear hidden' %>
	<%= link_to t('score.finished'), @score, class: 'finish hidden', remote: true %>
</div>

app/views/scores/_index.html.erb
<p id="notice"><%= notice %></p>

<ul>
  <li>
    <%= link_to t('score.new').html_safe, new_score_path %>
  </li>
  <% @scores.each do |score| %>
    <li>
      <%= score.name %>
      <%= score.score_type.name rescue 'Sesión libre' %>
      <%= score.state %>
      <%= score.published %>
      <%= score.points %>
      <%= score.average %>
      <%= link_to t('score.puntuar').html_safe, puntuar_score_path(score), remote: true %>
      <%= link_to t('main.show').html_safe, score, remote: true %>
      <%= link_to t('main.edit').html_safe, edit_score_path(score) %>
      <%= link_to t('main.destroy').html_safe, score, method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

app/views/scores/_keyboard.html.erb
<div class="keyboard">
	<div class="">
		<div class="arrow">
			<%= link_to 'X', '#', class: 'btn btn-arrow', remote: true, 'data-value': 10, 'data-arrow': 'X' %>
		</div>
		<div class="arrow">
			<%= link_to '10', '#', class: 'btn btn-arrow', remote: true, 'data-value': 10, 'data-arrow': '10' %>
		</div>
		<div class="arrow">
			<%= link_to '9', '#', class: 'btn btn-arrow', remote: true, 'data-value': 9, 'data-arrow': '9' %>
		</div>
		<div class="arrow">
			<%= link_to '8', '#', class: 'btn btn-arrow', remote: true, 'data-value': 8, 'data-arrow': '8' %>
		</div>
		<div class="arrow">
			<%= link_to '7', '#', class: 'btn btn-arrow', remote: true, 'data-value': 7, 'data-arrow': '7' %>
		</div>
		<div class="arrow">
			<%= link_to '6', '#', class: 'btn btn-arrow', remote: true, 'data-value': 6, 'data-arrow': '6' %>
		</div>
		<div class="arrow">
			<%= link_to '5', '#', class: 'btn btn-arrow', remote: true, 'data-value': 5, 'data-arrow': '5' %>
		</div>
		<div class="arrow">
			<%= link_to '4', '#', class: 'btn btn-arrow', remote: true, 'data-value': 4, 'data-arrow': '4' %>
		</div>
		<div class="arrow">
			<%= link_to '3', '#', class: 'btn btn-arrow', remote: true, 'data-value': 3, 'data-arrow': '3' %>
		</div>
		<div class="arrow">
			<%= link_to '2', '#', class: 'btn btn-arrow', remote: true, 'data-value': 2, 'data-arrow': '2' %>
		</div>
		<div class="arrow">
			<%= link_to '1', '#', class: 'btn btn-arrow', remote: true, 'data-value': 1, 'data-arrow': '1' %>
		</div>
		<div class="arrow">
			<%= link_to 'M', '#', class: 'btn btn-arrow', remote: true, 'data-value': 0, 'data-arrow': 'M' %>
		</div>
	</div>
</div>

<%= form_tag(add_arrows_score_path(@score), remote: true, id: 'form_arrows') do %>
	<%= hidden_field_tag 'arrow[val_1]' %>
	<%= hidden_field_tag 'arrow[val_2]' %>
	<%= hidden_field_tag 'arrow[val_3]' %>
	<%= hidden_field_tag 'arrow[val_4]' %>
	<%= hidden_field_tag 'arrow[val_5]' %>
	<%= hidden_field_tag 'arrow[val_6]' %>
<% end %>

<script>
	var total_arrows = <%= @score.score_type.arrows rescue 999 %>;
	var arrows = <%= @score.arrows.count %>;
	var total_points = $('#acumulacion');
	var avg = $('#media');
	var parcial = $('#parcial');
	var ronda_anterior = $('#ronda_anterior');
	var foco = 1;

	function ordenar() {
		var offset = foco;
		while(offset > 1){
			if(parseInt($('#arrow_'+offset).val()) > parseInt($('#arrow_'+(offset-1)).val()) || $('#arrow_'+offset).val() == 'X' || $('#arrow_'+(offset-1)).val() == 'M'){
				var aux = $('#arrow_'+(offset-1)).val();
				$('#arrow_'+(offset-1)).val($('#arrow_'+offset).val());
				$('#arrow_'+offset).val(aux);
			}
			offset--;
		}
	}

	$('.btn-arrow').click(function(event){
		event.stopPropagation();
		event.preventDefault();

		if(foco>0 && foco<7){
			var value = $(this).data('value');
			var arrow = $(this).data('arrow');

			total_points.html(parseInt(total_points.html())+value);
			parcial.html(parseInt(parcial.html())+value);

			$('#arrow_'+foco).val(arrow);
			// seteamos el hidden del formulario...
			$('#arrow_val_'+foco).val(arrow);
			suma_parcial(value);
			arrows++;
			// actualizamos la media
			avg.html((parseInt(total_points.html())/arrows).toFixed(2));
			
			if(foco == 6){
				$('#loading').removeClass('hidden');
				//enviamos el formulario
				$('#form_arrows').submit();
			}
			//reordenamos antes de aumentar el foco
			ordenar();
			//aumentamos el foco
			foco++;
			if(foco>6 || arrows == total_arrows || arrows > total_arrows){
				if(arrows == total_arrows || arrows > total_arrows) {
					$('.finish').removeClass('hidden');
				} else if(foco>6) {
					$('.resetear').removeClass('hidden');
				}

			}

		}
	});

	function suma_parcial(value) {
		if(foco < 4) {
			$('#partial_1').val(parseInt($('#partial_1').val())+value);	
		}else if(foco <7){
			$('#partial_2').val(parseInt($('#partial_2').val())+value);
		}
	}

	$('.resetear').click(function (event){
		event.stopPropagation();
		event.preventDefault();
		ronda_anterior.html(parcial.html());
		foco=1;
		parcial.html('0');
		$('.parciales').val(null);
		$('.suma_parcial').val(0);
		$('.resetear').addClass('hidden');
	});


</script>

app/views/scores/_menu.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
        <li>
            <%= link_to t('score.list_scores'), scores_path, remote: true %>
        </li>
        <%= render 'score_board' %>
    </ul>
</div>

app/views/scores/_partial_score.html.erb
<div class="partial_score">
	<div class="">
		<div class="arrow">
			<%= text_field_tag "arrow_1",'', id: 'arrow_1', class: 'parciales borde', disabled: true %>
		</div>
		<div class="arrow">
			<%= text_field_tag "arrow_2",'', id: 'arrow_2', class: 'parciales borde', disabled: true %>
		</div>
		<div class="arrow">
			<%= text_field_tag "arrow_3",'', id: 'arrow_3', class: 'parciales borde', disabled: true %>
		</div>
		<div class="arrow">
			<%= text_field_tag "partial_1",'0', id: 'partial_1', class: 'suma_parcial borde', disabled: true %>
		</div>
	</div>
	<div class="">
		<div class="arrow">
			<%= text_field_tag "arrow_4",'', id: 'arrow_4', class: 'parciales', disabled: true %>
		</div>
		<div class="arrow">
			<%= text_field_tag "arrow_5",'', id: 'arrow_5', class: 'parciales', disabled: true %>
		</div>
		<div class="arrow">
			<%= text_field_tag "arrow_6",'', id: 'arrow_6', class: 'parciales', disabled: true %>
		</div>
		<div class="arrow">
			<%= text_field_tag "partial_2",'0', id: 'partial_2', class: 'suma_parcial', disabled: true %>
		</div>
	</div>
</div>

app/views/scores/_puntuar.html.erb
<%= render 'scores/datos_parciales_score' %>
<%= render 'scores/partial_score' %>
<%= render 'scores/keyboard' %>

app/views/scores/_score_board.html.erb
<% acumulado = 0 %>
<% @arrows.in_groups_of(3) do |arrow| %>
	<% partial = arrow[0].value + arrow[1].value + arrow[2].value %>
	<% acumulado += partial %>
	<li>
		<%= arrow[0].arrow %> |
		<%= arrow[1].arrow %> |
		<%= arrow[2].arrow %> |
		<%= partial %> |
		<%= acumulado %>
	</li>
<% end %>

app/views/scores/_show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @score.name %>
</p>

<p>
  <strong>Score type:</strong>
  <%= @score.score_type_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @score.user_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @score.state %>
</p>

<p>
  <strong>Published:</strong>
  <%= @score.published %>
</p>

<p>
  <strong>Points:</strong>
  <%= @score.points %>
</p>

<p>
  <strong>Average:</strong>
  <%= @score.average %>
</p>

<p>
  <strong>X count:</strong>
  <%= @score.x_count %>
</p>

<p>
  <strong>Ten count:</strong>
  <%= @score.ten_count %>
</p>

<p>
  <strong>Nine count:</strong>
  <%= @score.nine_count %>
</p>

<%= link_to 'Edit', edit_score_path(@score), remote: true %> |
<%= link_to 'Back', scores_path, remote: true %>

app/views/scores/add_arrow.js.erb
$('#loading').addClass('hidden');

app/views/scores/add_arrows.js.erb
$('#loading').addClass('hidden');

app/views/scores/index.html.erb
<%= render 'index' %>

app/views/scores/index.js.erb
$("#app_container").html("<%= raw escape_javascript(render 'scores/index') %>");

app/views/scores/new.html.erb
<div class="acenter">
	<h2><%= t('score.new').html_safe %></h2>

	<%= render 'form' %>

	<%= link_to t('main.back').html_safe, scores_path %>
</div>

app/views/scores/puntuar.html.erb
<%= render 'scores/puntuar' %>